namespace Day6.Tests.Unit;

public class ProgramTests
{
	[Theory]
	[InlineData("""
		....#.....
		.........#
		..........
		..#.......
		.......#..
		..........
		.#..^.....
		........#.
		#.........
		......#...
		""")]
	public void DetermineCorrectPageOrdering_ShouldReturnCorrectTestResults(string input)
	{
		Assert.Equal(43, Program.Result(input));
	}
}
